### ISSUE TITLE
毎日がエブリデイでNetwork Error

### ISSUE THREAD

**Issue by yanorei32** [yr32infra/ksrgblog.yr32.net#12]
@KisaragiEffective

**Comment by KisaragiEffective** [comment]
外形監視

**Comment by yanorei32** [comment]
ところで、いつ治るんですか @KisaragiEffective

**Comment by KisaragiEffective** [comment]
blocked on https://github.com/KisaragiEffective/toy-blog/issues/350

**Comment by yanorei32** [comment]
Closeされてるけど？？？？

はよしろえふぇくてぃぶ

**Comment by KisaragiEffective** [comment]
various bugs need test

**Comment by yanorei32** [comment]
で、2週間たつけど？

**Comment by KisaragiEffective** [comment]
![image](https://github.com/yr32infra/ksrgblog.yr32.net/assets/48310258/dfceae0f-4b93-4d97-878c-388da0ed8664)
0.5系のAPIに対応してないので死んでる

**Comment by KisaragiEffective** [comment]
blocked on https://github.com/yr32infra/ksrgblog.yr32.net/pull/13

**Comment by yanorei32** [comment]
じゃああとは、復活させるだけなんで。よろぴく。

**Comment by KisaragiEffective** [comment]
![image](https://github.com/yr32infra/ksrgblog.yr32.net/assets/48310258/4b2baf60-21b6-416c-bb64-6f087e86cd7b)
ウケる

**Comment by KisaragiEffective** [comment]
0.6系統にならないと治らない

**Comment by KisaragiEffective** [comment]
work around: `2021..=(new Date().getFullYear())` で `GET /api/list/article/{year}`

**Comment by yanorei32** [comment]
ばぐらぎえふぇくてぃぶ

**Comment by yanorei32** [comment]
## 「らぎが悪いかも」 リターンズ @KisaragiEffective 


> work around: `2021..=(new Date().getFullYear())` で `GET /api/list/article/{year}`

今読んだけど、めちゃめちゃブログコンテンツに依存しているし、何がワークアラウンドやねん。

https://blog.ksrgte.ch/api/list/article/2022 を叩くと

```json
["i-will-not-forgive-those","switched-to-debian11","hello","理想と現実の違い","what-is-mercy"]
```

だけど……？？？

え？？？ 日付情報は？？？

**Comment by KisaragiEffective** [comment]
~~blocked on KisaragiEffective/toy-blog#376~~

**Comment by KisaragiEffective** [comment]
toy-blog 0.6.0のリリース待ち

**Comment by yanorei32** [comment]
うん、頑張って…？

**Comment by KisaragiEffective** [comment]
@yanorei32 fixed on prod 🎉

**Comment by yanorei32** [comment]
新API対応したので、Close。
